#!/bin/bash

# Load maven specific env vars
source /etc/profile.d/maven-env.sh

# We implement this env var mainly for debugging
# purpose, since this is not recognized by maven
export USER_HOME=$(dirname ${MAVEN_M2DIR})

exec "$@"
