#!/bin/bash

# We implement this env var mainly for debugging
# purpose, since this is not recognized by maven
export USER_HOME=${HOME}

# Load maven specific env vars
source /etc/profile.d/maven-env.sh

[ -n "${DEBUG}" ] && echo exec "$*" >&2

exec "$@"
