#!/bin/bash
#
# Wrapper script for the original mvn executable
#
# Set the correct ${user.home} options using the dedicated env var
#

debug=${DEBUG}
userland=${HOME}

_exec(){
    [ -n "${debug}" ] && printf "[%s] %s\n" "$(basename $0)" "${*}"
    "${@}"
    return $?
}

for arg
do
    case ${arg} in
        # Support passing options in the --option=value form
        --*=*)
            arg=$1
            option=${arg%%=*}
            value=${arg##*=}
            shift 1
            set -- ${option} ${value} $@
            ;;
        # Allow overriding the ${user.home} variable
        -Duser.home)
            userland=${2}
            shift 2
            ;;
        # When invoked in quiet mode, no debug messages
        -q)
            debug=
            ;;
    esac
done

#[ -n "${debug}" ] && echo ${MAVEN_HOME}/bin/mvn -Duser.home=${userland} "$*"

_exec ${MAVEN_HOME}/bin/mvn -Duser.home=${userland} "$@"
