#!/bin/bash

latest=19

[ $# -eq 0 ] && set -- 16 17 18 19

for jdk in "$@"
do
    #git checkout 3.8/openjdk/${jdk}

    docker build --build-arg JDK_VERSION=${jdk} -t yannoff/maven:${jdk}-jdk ./

    if [ "$?" != "0" ]
    then
        echo "[publish] Building base image yannoff/maven:${jdk}-jdk failed. Exiting"
        exit 1
    fi

    for tag in 3.8.5-openjdk-${jdk}-alpine 3.8.5-openjdk-${jdk} 3.8-openjdk-${jdk}
    do
        docker tag yannoff/maven:${jdk}-jdk yannoff/maven:${tag}
        docker push -q yannoff/maven:${tag}
    done

    #git checkout -
done

docker tag yannoff/maven:${latest}-jdk yannoff/maven:latest
docker push -q yannoff/maven:latest
