#!/bin/bash

latest=19
image=yannoff/maven

[ $# -eq 0 ] && set -- 16 17 18 19

for jdk in "$@"
do
    tags=( 3.8.5-openjdk-${jdk}-alpine 3.8.5-openjdk-${jdk} 3.8-openjdk-${jdk} 3-openjdk-${jdk} )

    docker build \
        --build-arg JDK_VERSION=${jdk} \
        -t ${image}:${jdk}-jdk \
        ./

    if [ "$?" != "0" ]
    then
        echo "[publish] Building base image ${image}:${jdk}-jdk failed. Exiting"
        exit 1
    fi

    for tag in "${tags[@]}"
    do
        docker tag ${image}:${jdk}-jdk ${image}:${tag}
        docker push -q ${image}:${tag}
    done

    if [ "${jdk}" = "${latest}" ]
    then
        docker tag ${image}:${jdk}-jdk ${image}:latest
        docker push -q ${image}:latest
        docker rmi -f ${image}:latest
    fi

    for tag in ${jdk}-jdk "${tags[@]}"
    do
         docker rmi -f ${image}:${tag}
    done
    docker rmi -f openjdk:${jdk}-alpine

done


